name: Checklist ✅
description: Stepwise process or review
type: 'Checklist ✅'
projects: ["StaytunedLLP/43"]

body:
  - type: markdown
    attributes:
      value: Let AI build, be orchestrator, ship instantly. 🤖🪄🚀

  - type: textarea
    attributes:
      label: Description
      value: |
        ### Objective
        <!-- Say what this checklist should verify or complete. -->

        

        ### Checklist
        <!-- Link <filename>.checklist.md file path -->

        - [Filename](www.github.com)

        ### Blockers
        <!-- List only blockers that stop progress. -->
        
        - None

        ### Context